### ISSUE TITLE
Fix with paws?

### ISSUE THREAD

**Issue by seankross** [jhudsl/text2speech#1]
This package is throwing warnings on CRAN: https://cran.r-project.org/web/checks/check_results_text2speech.html

Maybe replace all of the Amazon stuff with Paws? https://github.com/paws-r/paws

**Comment by muschellij2** [comment]
Thanks - I'm corresponding with CRAN right now.  ANy chance you can send a
pull request?
Best,
John

**Comment by seankross** [comment]
I likely can't this week.
