### ISSUE TITLE
Use short name for voices from Microsoft service

### ISSUE THREAD

**Issue by boltomli** [jhudsl/text2speech#2]
Currently the result from `tts_microsoft_voices()` maps full name that is very long. Short name is preferred for a cleaner output and use.

Here's a screenshot for example:

![screenshot_2020-04-15_16-20-36](https://user-images.githubusercontent.com/5236916/79332306-32d22c00-7f4f-11ea-8069-b51c03a012dd.png)

Short names would be better for UI without user code change. What is your opinion?

**Comment by muschellij2** [comment]
I don't think so.  These are the required voices to pass
to mscstts::ms_synthesize.
Best,
John

**Comment by boltomli** [comment]
Yes, it was the case before to use the voice name to synthesize. But short name of the voices was added to be usable too. In the [sample](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/rest-text-to-speech#sample-request-1) it's like this now:

```
POST /cognitiveservices/v1 HTTP/1.1

X-Microsoft-OutputFormat: raw-16khz-16bit-mono-pcm
Content-Type: application/ssml+xml
Host: westus.tts.speech.microsoft.com
Content-Length: 225
Authorization: Bearer [Base64 access_token]

<speak version='1.0' xml:lang='en-US'><voice xml:lang='en-US' xml:gender='Female'
    name='en-US-AriaRUS'>
        Microsoft Speech Service Text-to-Speech API
</voice></speak>
```

It will also save some spaces when POST SSML with many voices together in one request.

**Comment by muschellij2** [comment]
Where is this shiny app?

**Comment by boltomli** [comment]
Oh, I am trying to make a shiny web app so it's easy to try the major services online. The repo is <https://github.com/boltomli/shiny-speech>, still at an early stage.

Now with a proper key and region, I'd call `mscstts` directly to get voices list from API.

![截图_2020-04-17_08-46-07](https://user-images.githubusercontent.com/5236916/79520156-94e27c80-8088-11ea-9629-9b899570dcd2.png)

When no key is given, `tts_voices(service = "microsoft")` is fine.

**Comment by muschellij2** [comment]
Given your change, is this resolved?
