### ISSUE TITLE
Submit updates to CRAN 

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/text2speech#27]
We'll need to submit updates to CRAN. I'm not sure what this will look like since Muschelli is the creator, but let's try to submit an update and see what happens. 

1. Update the version number a good chunk since these were substantial edits. 
2. Run `devtools::build()` in the code base for the package. 
3. Go here to submit: https://cran.r-project.org/submit.html

**Comment by muschellij2** [comment]
You can run devtools::release() to do this, it also checks it.
Best,
John

**Comment by howardbaek** [comment]
@muschellij2  do you mind if I take over as maintainer of this package?

**Comment by howardbaek** [comment]
See https://github.com/jhudsl/text2speech/issues/35
