### ISSUE TITLE
Other text engines

### ISSUE THREAD

**Issue by BAREJAA** [jhudsl/text2speech#3]
Does text2speech work for text engines other than Amazon, Microsoft, and Google?

**Comment by muschellij2** [comment]
What other engines are you thinking?   I'm trying to unify the interface a bit with one command so there needs to be an existing package.

**Comment by BAREJAA** [comment]
This one that allows the user to use their own voice - https://www.descript.com/overdub

**Comment by muschellij2** [comment]
Can you point me to the R package that is implemented for their API?  Because I am only connecting pieces, not implementing new API mappings.  I'm open to PRs.  So if you find it, please reopen and send a PR.

**Comment by BAREJAA** [comment]
I don't think there is one. But thank you for the information and the offer!
